
@base_url = http://localhost:5050

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI2OTdkZDA3Y2FiNDE3YmRjMDk1MzU4ZTQiLCJpYXQiOjE3NzIwMTIyODIsImV4cCI6MTc3MjA5ODY4Mn0.uwDeb4hkPhOW1q-b1nYTJwEmEI9AtKcv_VHZ3xrgjVc

###
POST {{base_url}}/admin/auth/login
Content-Type: application/json

{
  "fullName": "Phung Van Duy",
  "email": "admin@gmail.com",
  "password": "123"
}


// api_user
### 
POST {{base_url}}/admin/users/create 
Content-Type:  application/json
header : Bearer {{token}}

{
  "fullName" : "hr-test1" ,
  "email" : "test1@gmail.com",
  "password" : "123"
}

###
GET  {{base_url}}/admin/users 
header : Bearer {{token}}

// end api_user